# Generated by Django 3.1.7 on 2021-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.IntegerField(choices=[(-1, 'not defined'), (0, 'rock'), (1, 'metal'), (2, 'pop'), (3, 'hip hop'), (4, 'electronic')], default=-1),
        ),
        migrations.AddField(
            model_name='band',
            name='still_activate',
            field=models.BooleanField(default=True),
        ),
    ]
