# Generated by Django 3.1.7 on 2021-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0005_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'awful'), (1, 'weak'), (2, 'so so'), (3, 'good'), (4, 'very good'), (5, 'excelLent')])),
            ],
        ),
    ]
